#ifndef DGLOBALS_HPP
#define DGLOBALS_HPP

#define PROGRAM_VERSION_MAJOR "0"
#define PROGRAM_VERSION_MINOR "1"
#define PROGRAM_VERSION_BUILD "34"
#define PROGRAM_VERSION_RELEASE_TYPE " Alpha"

#define PROGRAM_VERSION_STRING \
    PROGRAM_VERSION_MAJOR "." PROGRAM_VERSION_MINOR "." PROGRAM_VERSION_BUILD

#define PROGRAM_VERSION_FULL_STRING \
    PROGRAM_VERSION_STRING PROGRAM_VERSION_RELEASE_TYPE

#endif // DGLOBALS_HPP
